on:
  push:
    branches:
    - main
    paths:
    - Dockerfile

jobs:
  build-image:
    name: Build tesla-vehicle-command
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        run: |
          IMAGE=ghcr.io/mikesmitty/tesla-vehicle-command:$(awk -F= '/APP_VERSION *=/ {print $2}' Dockerfile)-$(date +%F)
          docker build -t $IMAGE .
          docker push $IMAGE
